name: chucker_flutter
description: Chucker Flutter helps you inspect the HTTP(S) requests/responses. It stores data locally and provides a UI for inspecting network calls and sharing their content.
version: 1.3.6
repository: https://github.com/syedmurtaza108/chucker-flutter
issue_tracker: https://github.com/syedmurtaza108/chucker-flutter/issues
funding:
  - https://www.patreon.com/syedmurtaza
isar_version: &isar_version 3.1.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  chopper: ^5.1.0
  dio: ^4.0.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.4
  http_mock_adapter: ^0.3.2
  share_plus: ^5.0.0
  shared_preferences: ^2.0.13
  isar: *isar_version
  isar_flutter_libs: *isar_version # contains Isar Core
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0
  isar_generator: *isar_version
  build_runner: ^2.3.2
  freezed: ^2.3.2
  # Json serialization generator
  json_serializable: ^6.4.0
