name: chucker_flutter
description: Chucker Flutter helps you inspect the HTTP(S) requests/responses. It stores data locally and provides a UI for inspecting network calls and sharing their content.
version: 1.7.2
repository: https://github.com/syedmurtaza108/chucker-flutter
issue_tracker: https://github.com/syedmurtaza108/chucker-flutter/issues
topics: [ http, networking, chucker ]
funding:
  - https://www.patreon.com/syedmurtaza

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

dependencies:
  chopper: ^7.0.8
  dio: ^5.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.0.0
  http_mock_adapter: ^0.6.0
  share_plus: ^9.0.0
  shared_preferences: ^2.0.13
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  isar_generator: ^3.1.0+1

screenshots:
  - description: Chucker Flutter Logo
    path: screenshots/logo.png